### RESET PASSWORD
POST https://simple-email-sender.vercel.app/send HTTP/1.1
content-type: application/json 

{
    "emailData": {
         "senderName" :" noa",
         "subject" : "Contact",
         "emailBody": "this the body"
    },
    "email" :"09vbv.009@gmail.com"
        
    
}
